channels:
- anaconda
- defaults
- conda-forge
dependencies:
- click=8.0.4
- ipykernel=6.25.2
- matplotlib=3.7.2
- menuinst=2.0.0
- numpy=1.26.0
- pandas=2.0.3
- pdf2image=1.16.3
- polars=0.19.3
- python=3.11.5
- python-dotenv=0.21.0
- python-pptx=0.6.22
- seaborn=0.12.2
- xlsx2csv=0.8.1
- xlsxwriter=3.1.1
- pip:
  - cytoolz==0.12.2
  - pyarrow==13.0.0
  - pyyaml==6.0.1
  - toolz==0.12.0
name: egresos-deis
