name: egresos-deis
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.7.2
  - numpy=1.26.0
  - seaborn=0.12.2
  - pandas=2.0.3
  - python
  - polars=0.19.3
  - ipykernel=6.25.2
  - click=8.0.4
  - python-dotenv=0.21.0
  - xlsx2csv=0.8.1
  - xlsxwriter=3.1.1
  - pip:
      - pyarrow==13.0.0
      - pyyaml==6.0.1
